tasks:
  - name: Install AWS CLI tool and setup tab completion
    init: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      aws --version
      complete -C '/usr/bin/aws_completer' aws


vscode:
  extensions:
    - 42Crunch.vscode-openapi